name: Extract Boot Images from OTA

on:
  workflow_dispatch:
    inputs:
      ota_url:
        description: 'OTA Package URL'
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS2.0.215.0.VMBCNXM/nuwa-ota_full-OS2.0.215.0.VMBCNXM-user-15.0-03badd90e8.zip'
      partitions:
        description: 'Partitions to extract (comma-separated)'
        required: true
        default: 'boot,dtbo,init_boot,vbmeta,vendor_boot'
      release_tag:
        description: 'Release tag name'
        required: true
        default: 'v1.0'

jobs:
  extract-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install payload-dumper
        run: pip install git+https://github.com/5ec1cff/payload-dumper
      
      - name: Extract partition images (streaming from URL)
        run: |
          mkdir -p out
          payload_dumper --partitions ${{ github.event.inputs.partitions }} \
            "${{ github.event.inputs.ota_url }}"
          
          echo "=== Extracted files ==="
          ls -lh out/
          
          cd out && sha256sum * > SHA256SUMS.txt && cat SHA256SUMS.txt
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: partition-images-${{ github.event.inputs.release_tag }}
          path: out/
          retention-days: 30
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Partition Images ${{ github.event.inputs.release_tag }}
          body: |
            ## Extracted Partition Images
            
            **OTA Source:** `${{ github.event.inputs.ota_url }}`
            **Partitions:** ${{ github.event.inputs.partitions }}
            
            ### SHA256 Checksums
            ```
            $(cat out/SHA256SUMS.txt)
            ```
          files: |
            out/*.img
            out/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}